version: 0.2

phases:
  build:
    commands:
      - pwd
      - echo 'hello Ben'
      - ls -al
      - pip install -r $CODEBUILD_SRC_DIR/pdftotext/requirements.txt
      - python $CODEBUILD_SRC_DIR/pdftotext/process.py > well_architected_framework.txt
      - aws s3 cp ${CODEBUILD_SRC_DIR}/pdftotext/well_architected_framework.txt s3://pollywhitepapers/pdftotext

#artifacts:
#  files:
#     - pdftotext/well_architected_framework.txt
#  discard-paths: yes
#  base-directory: ${CODEBUILD_SRC_DIR}